// packages/todo-vue-cartons/src/components/todos.vue
<template>
<section class="main">
    <input
      id="toggle-all"
      class="toggle-all"
      type="checkbox"
      @change="toggleAll()"
      :checked="todos.isAllCompleted()"
    />
    <label
      htmlFor="toggle-all"
    />
    <div
      class="todo-list"
    >
      <TodoItem
        v-for="todo in filterItems"
        :key="todo.key"
        :todo="todo"
        :remove="todos.actions.removeTodo"
      />
    </div>
  </section>
</template>

<script>
import TodoItem from './todo-item';

export default {
  components: {
    TodoItem
  },
  props: ['todos'],

  computed: {
    filterItems: function () {
      console.log('get filterItems')
      return this.todos.getFilterItems();
    }
  },

  methods: {
    toggleAll: function () {
      this.todos.actions.toggleAllCompleted();
    }
  }
}
</script>

// packages/todo-react-cartons/src/components/todos.jsx
import * as React from 'react';

import { observer } from 'cartons-react';

import TodoItem from './todo-item';

@observer()
export default class Todos extends React.Component {
  render () {
    const todos = this.props.todos;

    return (
      <section className="main">
        <input
          id="toggle-all"
          className="toggle-all"
          type="checkbox"
          onChange={this.toggleAll}
          checked={todos.isAllCompleted()}
        />
        <label
          htmlFor="toggle-all"
        />
        <div
          className="todo-list"
        >
          {this.renderTodos()}
        </div>
      </section>
    )
  }

  renderTodos () {
    const todos = this.props.todos;

    return todos.getFilterItems().map((todo, index) => (
      <TodoItem
        key={todo.key}
        todo={todo}
        remove={todos.actions.removeTodo}
        // edit={editTodo}
        // modifyCompleted={modifyTodoCompleted}
      />
    ))
  }

  toggleAll = () => {
    this.props.todos.actions.toggleAllCompleted();
  }
}
