// packages/todo-vue-cartons/src/components/todo-item.vue
<template>
<div
  :class="`todo-item${editing ? ' editing' : ''}${todo.completed ? ' completed' : ''}`"
>
  <input
    v-if="editing"
    class="edit"
    type="text"
    @keyDown="handleKeyDown($event)"
    @input="handleChangeEditText($event)"
    :value="editText"
    autoFocus="true"
  />
  <div
    v-else
  >
    <input
      class="toggle"
      type="checkbox"
      :checked="todo.completed"
      @change="todo.actions.toggleComplete()"
    />
    <label @doubleClick="handleToEdit($event)">
      {{todo.title}}
    </label>
    <button class="destroy" @click="handleDestroy()" />
  </div>
</div>
</template>

<script>
const ESCAPE_KEY = 27;
const ENTER_KEY = 13;

export default {
  props: ['todo', 'remove'],
  data: function () {
    return {
      editing: false,
      editText: ''
    }
  },

  methods: {
    handleDestroy: function () {
      const {
        remove,
        todo
      } = this;
      this.remove(todo);
    },

    handleToEdit: function () {
      this.editing = true,
      this.editText = this.todo.title;
    },

    handleChangeEditText: function (event) {
      this.editText = event.target.value;
    },

    handleKeyDown: function (event) {
      if (event.which === ESCAPE_KEY) {
        this.cancelEdit();
        event.preventDefault();
      } else if (event.which === ENTER_KEY) {
        this.editComplete();
        event.preventDefault();
      }
    },

    cancelEdit: function () {
      this.editing = false;
    },

    editComplete: function () {
      this.editing = false;
      this.todo.actions.editTodo(this.editText);
    }
  }
}
</script>

// packages/todo-react-cartons/src/components/todo-item.jsx
import * as React from 'react';

const ESCAPE_KEY = 27;
const ENTER_KEY = 13;


export default class TodoItem extends React.Component {
  state = {
    editing: false
  }

  renderEditing () {
    return (
      <input
        className="edit"
        type="text"
        onKeyDown={this.handleKeyDown}
        onChange={this.handleChangeEditText}
        value={this.state.editText}
        autoFocus={true}
      />
    );
  }

  renderStatic () {
    const { todo } = this.props;
    return (
      <div>
        <input
          className="toggle"
          type="checkbox"
          checked={todo.completed}
          onChange={todo.actions.toggleComplete}
        />
        <label onDoubleClick={this.handleToEdit}>
          {todo.title}
        </label>
        <button className="destroy" onClick={this.handleDestroy} />
      </div>
    );
  }

  render () {
    const {
      editing
    } = this.state;
    const {
      todo
    } = this.props;
    return (
      <div
        className={`todo-item${editing ? ' editing' : ''}${todo.completed ? ' completed' : ''}`}
      >
        {editing
          ? (this.renderEditing())
          : (this.renderStatic())
        }
      </div>
    )
  }

  handleDestroy = () => {
    const {
      remove,
      todo
    } = this.props;
    remove(todo);
  }

  handleToEdit = () => {
    this.setState({
      editing: true,
      editText: this.props.todo.title
    })
  }

  handleChangeEditText = (event) => {
    this.setState({ editText: event.target.value });
  }

  handleKeyDown = (event) => {
    if (event.which === ESCAPE_KEY) {
      this.cancelEdit();
      event.preventDefault();
    } else if (event.which === ENTER_KEY) {
      this.editComplete();
      event.preventDefault();
    }
  }

  cancelEdit () {
    this.setState({ editing: false });
  }

  editComplete () {
    this.setState({ editing: false });
    this.props.todo.actions.editTodo(this.state.editText);
  }
}
