// packages/todo-vue-cartons/src/components/footer.vue
<template>
<div class="footer">
  <div class="todo-count">
    <strong>{{todos.length}}</strong> items
  </div>
  <ul class="filters">
    <li>
      <a
        href="javascript:"
        :class="todos.filterType === 'ALL' ? 'selected' : ''"
        @click="handleFilterShow('ALL')"
      >All</a>
    </li>
    <li>
      <a
        href="javascript:"
        :class="todos.filterType === 'ACTIVE' ? 'selected' : ''"
        @click="handleFilterShow('ACTIVE')"
      >Active</a>
    </li>
    <li>
      <a
        href="javascript:"
        :class="todos.filterType === 'COMPLETED' ? 'selected' : ''"
        @click="handleFilterShow('COMPLETED')"
      >Completed</a>
    </li>
  </ul>
  <button
    class="clear-completed"
    @click="todos.actions.clearAllCompleted()"
  >
    Clear completed
  </button>
</div>
</template>

<script>
export default {
  props: ['todos'],

  methods: {
    handleFilterShow: function (type) {
      this.todos.actions.goFilterTodos(type);
    }
  }
}
</script>

// packages/todo-react-balloon/src/components/footer.jsx
import * as React from 'react';

import todoCollection, { actions } from '../store/todo-collection';
import { connect } from './connect';

@connect(
  {
    todoCollection
  },
  {
    goFilterTodos: actions.goFilterTodos,
    clearAllCompleted: actions.clearAllCompleted
  }
)
export default class Footer extends React.Component {
  render () {
    const { todoCollection, goFilterTodos, clearAllCompleted } = this.props;
    const filterType = todoCollection.get('filterType');
    return (
      <div className="footer">
        <div className="todo-count">
          <strong>{todoCollection.length}</strong> items
        </div>
        <ul className="filters">
          <li>
            <a
              href="javascript:"
              className={filterType === 'ALL' ? 'selected' : ''}
              onClick={() => (goFilterTodos('ALL'))}
            >All</a>
          </li>
          <li>
            <a
              href="javascript:"
              className={filterType === 'ACTIVE' ? 'selected' : ''}
              onClick={() => (goFilterTodos('ACTIVE'))}
            >Active</a>
          </li>
          <li>
            <a
              href="javascript:"
              className={filterType === 'COMPLETED' ? 'selected' : ''}
              onClick={() => (goFilterTodos('COMPLETED'))}
            >Completed</a>
          </li>
        </ul>
        <button
          className="clear-completed"
          onClick={clearAllCompleted}
        >
          Clear completed
        </button>
      </div>
    )
  }
}
